export const commitlintConfigMjs = 'commitlint.config.mjs'
export const packageJson = 'package.json'
export const husky_commitMsg = '.husky/commit-msg'
export const husky_preCommit = '.husky/pre-commit'
export const pnpmWorkspaceYaml = 'pnpm-workspace.yaml'
